### ISSUE TITLE
Hi, would you supply the script of speed test?

### ISSUE THREAD

**Issue by tbwxmu** [DrrDom/pmapper#1]
Thank you for sharing your code. would you supply the script of speed test?

**Comment by DrrDom** [comment]
Sure, that should not be too difficult. But what would you expect from this test?
I can create a test similar to that one which I used in the past and inserted results in README. It will measure calculation time for pharmacophores with different number of features. Is it what you want?

**Comment by tbwxmu** [comment]
yes, look forward to your update. I expect to use a fast pharmacophore matching function as a scoring function in virtual screening.

**Comment by DrrDom** [comment]
OK, I'll do this and add to the package. However, virtual screening is not simply matching of hashes. If hashes is identical it means that pharmacophores have the same set of features with similar spatial arrangement. But this is not suitable if you would like to match a query pharmacophore to a subset of features of a target pharmacophore. Of course, one may enumerate hashes for all subsets of features and looking for identity with a query pharmacophore, but I believe that it can be suitable only for relatively small target pharmacophores (7-9 features) and relatively large query pharmacophores (5-6). Otherwise combinatorics may be too unfavorable.
There is a function `fit_model`, but it current implementation is rather slow and can be improved. Therefore, for fast screening I can propose to consider `psearch` package and `screen_db` script. But it would require to create database of pharmacophores for conformers first with `prepare_db`. This screening is optimized to match many query pharmacophores at once.

**Comment by DrrDom** [comment]
I added `pmapper_speed_test` as a command line utility. You can update the package and try it. I also updated speed test results with those obtained with this script. Hope it would be helpful.

**Comment by tbwxmu** [comment]
Thanks for your help. I want to know if you have a plan to add the "Pharmacophore Matching Similarity" function?

**Comment by DrrDom** [comment]
What do you mean under this term?
Currently you can calculate fingerprints for a pharmacophore of any complexity (number of features) and length using `get_fp` function. After that you may apply any similarity measure. But be careful with setup, because choosing fingerprints with 4 features may result in many combinations and activated bits for pharmacophores with many features. You need to choose proper length of fingerprints to have reasonable bit density. 
Alternatively you may use `calc_descriptors` function which returns the count-based vector of features with names of quadruplets and their occurrence in a pharmacophore.
