### ISSUE TITLE
Visualize the models?

### ISSUE THREAD

**Issue by suneelbvs** [DrrDom/pmapper#2]
Hi,

Thanks for sharing the script and nice tutorial on how to generate pharmacophore models. Will it be possible to view (pymol or nglview) the generated pharmacophore models for analysis purpose. I have tried to generate .xyz file and but wasnt successful. Any help will be appreciated!.

Thanks in advance.

Regards,
Suneel

**Comment by DrrDom** [comment]
Pymol can visualize pharmacophore features in xyz-files as spheres. Not always convenient but currently this is the only way.
If you failed to generate xyz-file please provide a reproducible example. Otherwise, I would not be able to help.

**Comment by suneelbvs** [comment]
@DrrDom , thanks for your reply. Yes it worked in pymol (as attached). But i couldn't differentiate the pharmacophore features (as acceptor, aromatic, and donor?). Did i miss any options here?.

Also, can i able to export respective 3D conformation used for pharmacophore model? so that i can overlap with generated pharmacophore model for anlaysis?. Thanks again. looking forward for your suggestions.


![image](https://user-images.githubusercontent.com/334679/82735024-433ea900-9d3c-11ea-847a-b9e111840cbf.png)

**Comment by DrrDom** [comment]
You may click on spheres to look at the "atom" name. A - acceptor, D - donor, a - aromatic, H - hydrophobic, P- positive, N - negative. Features which have identical coordinates overlap and in this case it is more difficult to understand. You may enable transparency to see if some features are inside, but this will only partially solve the problem.
I thought about a plugin to visualize pharmacophores as transparent spheres of different color and and size, but this is a low priority task.

If you additionally open the molecule which was used to generate the pharmacophore they will be overlapped, because the generated pharmacophore will have the same coordinates. Making features transparent will allow to see how structure align with pharmacophore.

**Comment by suneelbvs** [comment]
Thanks @DrrDom for clarification and quick response. Yes, that plug-in might help to configure the sphere and assign colors based on the features. 

For meanwhile, we can also try to assign the colors based on the features (its more of manual work). select the feature and color > select standard color (red - acceptor, blue - donor, etc., ). It might solve the problem temporarily. Hope it make sense.

![image](https://user-images.githubusercontent.com/334679/82736691-3ffdea00-9d49-11ea-80d6-f91139370d2c.png)

**Comment by DrrDom** [comment]
Yes, this makes sense, we do the same if we want to visualize pharmacophores.
