### ISSUE TITLE
psearch functionality

### ISSUE THREAD

**Issue by spadavec** [DrrDom/pmapper#5]
Hello 

I see a reference to a "psearch" functionality for high throughput pharmacophore screening, but can't seem to find it anywhere. Can that be shared? If not, what are the best ways to screen a large collection of molecules (1M+) against a few point pharmacophore?

**Comment by DrrDom** [comment]
Hi Vito,

there are few options:
1) Use our psearch software from this branch of the repo https://github.com/meddwl/psearch/tree/dev2. You will need to generate a database of conformers and pharmacophores for each molecule. The drawback of our approach that some molecules can be missed due to fuzzy matching. However, the fewer points in a query will be the less number of compounds will be missed.
2) Use pharmit software of David Koes - https://sourceforge.net/p/pharmit/code/ci/master/tree/src/. You will still need to generate a database of conformers and pharmacophores. The generation of a database may take longer and it can be larger, but screening will be very fast. So, if you will be able to install it, I would recommend it for screening. It uses true 3D alignment.

I do not know what would be more effective for a pharmacophore with a small number of features. How many features are in your pharmacophore?

Pavel.

**Comment by RJ-Li** [comment]
Hello, I see this method to compare two molecules, can we use this to do large-scale screening?
(I don't know what the load_from_feature_coords means and why the output is a tuple)
```
Pharmacophore match
Create a two-point pharmacophore model and match with a pharmacophore of a molecule (both pharmacophores should have identical binning steps)

q = P()
q.load_from_feature_coords([('a', (3.17, -0.23, 0.24)), ('D', (-2.51, -1.28, -1.14))])
p.fit_model(q)
Output

(0, 1)
```

**Comment by DrrDom** [comment]
Moved to a separate issue
