### ISSUE TITLE
ligandscout

### ISSUE THREAD

**Issue by caominhtruong** [DrrDom/pmapper#9]
How to load and read file .pml from ligandscout from your code?
I have a pharmacophore created in LigandScout and I want to open and perform virtual screening by your code

**Comment by DrrDom** [comment]
This should work
```python
from pmapper.pharmacophore import Pharmacophore as P
p  = P()
# load LS model
p.load_ls_model('filename.pml')
# save LS model
p.save_ls_model('filename.pml', name='optional_name_visible_in_LS')
```

**Comment by caominhtruong** [comment]
1. I encountered this error (picture attached below)
2. Is there any way to perform pharmacophore modelling by pmapper but not psearch?
![download](https://github.com/DrrDom/pmapper/assets/141115740/01dcb0b9-a999-4fd7-99d7-3dfca44db443)

**Comment by DrrDom** [comment]
1. I do not see the full text of the error, insert full text of the error message. If the problem is in line 836, then maybe some feature names were changed in recent versions of LigandScout. This is a very experimental option to support LS files. You may attach pml-file to look on it.
2. The question is unclear. What kind of modeling do you mean?

**Comment by caominhtruong** [comment]
For my 2nd question:
Is there any way to create a pharmacophore model based on multiple ligands by pmapper?

**Comment by DrrDom** [comment]
No, there is no a built-in procedure. This will require to implement a full modeling procedure.

**Comment by caominhtruong** [comment]
Because I have encountered the problem when building pharmacophore model by psearch. When i build model, there is nothing in external_statistics file and models, results folder
